name: Install and start RKE2
runs:
  using: composite
  steps:
    - run: |
        sudo mkdir -p /etc/rancher/rke2/config.yaml.d
        if [ -e /var/run/crio/crio.sock ] ; then
            echo "container-runtime-endpoint: /var/run/crio/crio.sock" | sudo tee /etc/rancher/rke2/config.yaml.d/70-crio.yaml
        elif [ -e /var/run/containerd/containerd.sock ] ; then
            echo "container-runtime-endpoint: /var/run/containerd/containerd.sock" | sudo tee /etc/rancher/rke2/config.yaml.d/70-containerd.yaml
        fi

        curl -sfL https://get.rke2.io | sudo sh -
        sudo systemctl start rke2-server.service
        systemctl status rke2-server.service
        mkdir ~/.kube
        sudo cat /etc/rancher/rke2/rke2.yaml > ~/.kube/config
        sudo ln -s /var/lib/rancher/rke2/bin/kubectl /usr/local/bin
        ( set +x ; while true ; do if kubectl get nodes | tee /dev/stderr | grep -q '\bReady\b' ; then break ; else sleep 5 ; fi ; done )
        ( set +x ; while ! kubectl get serviceaccount/default ; do sleep 5 ; done )
        kubectl get pods --all-namespaces
        ( set +x ; while kubectl get pods -A 2>&1 | grep -E 'Pending|ContainerCreating|Init|No resources found' ; do echo --- ; sleep 5 ; done )
        kubectl get all -A

        kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
        kubectl patch storageclass local-path -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
      shell: bash -euxo pipefail {0}
