kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        feature-gates: KubeletInUserNamespace=true
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        feature-gates: KubeletInUserNamespace=true
networking:
  apiServerPort: 6443
  apiServerAddress: 0.0.0.0
# Even with 0.0.0.0 uncommented, we still want to have 127.0.0.1 in the certificate
kubeadmConfigPatchesJSON6902:
- group: kubeadm.k8s.io
  version: v1beta4
  kind: ClusterConfiguration
  patch: |
    - op: add
      path: /apiServer/certSANs/-
      value: 127.0.0.1
