apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kind-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: kind-cluster
  labels:
    app: kind-cluster
spec:
  initContainers:
  - name: create-cluster
    image: localhost/kind
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    command:
    - kind
    - create
    - cluster
    - --config
    - /etc/kind-cluster-rootless.yaml
    volumeMounts:
    - mountPath: /var/lib/containers
      name: var-lib-containers
    - mountPath: /etc/containers/networks/kind.json
      name: podman-config
      subPath: kind-network.json
      readOnly: true
  containers:
  - name: run-cluster
    image: quay.io/podman/stable
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    command:
    - bash
    - -c
    - 'podman start --all && sleep infinity'
    volumeMounts:
    - mountPath: /var/lib/containers
      name: var-lib-containers
    - mountPath: /etc/containers/networks/kind.json
      name: podman-config
      subPath: kind-network.json
      readOnly: true
  volumes:
  - name: var-lib-containers
    persistentVolumeClaim:
      claimName: kind-pvc
  - name: podman-config
    configMap:
      name: podman-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: podman-config
data:
  kind-network.json: |
    {
     "name": "kind",
     "id": "7beee7286e2c3a88e9dd722262253e10087cfc322dc1a9302c432479809caa88",
     "driver": "bridge",
     "network_interface": "podman1",
     "created": "2023-12-06T07:53:45.286829744Z",
     "subnets": [
          {
               "subnet": "10.89.0.0/24",
               "gateway": "10.89.0.1"
          }
     ],
     "ipv6_enabled": false,
     "internal": false,
     "dns_enabled": true,
     "ipam_options": {
          "driver": "host-local"
     }
    }
