name: Configure systemd containerd
runs:
  using: composite
  steps:
    - run: |
        sudo mkdir -p /etc/containerd
        # remove the default config which has disabled_plugins = ["cri"]
        sudo rm -f /etc/containerd/config.toml
        sudo systemctl restart containerd
        sudo cp .github/actions/containerd-config-k3s.toml /etc/containerd/
      shell: bash -euxo pipefail {0}
