name: Configure systemd containerd
runs:
  using: composite
  steps:
    - run: |
        sudo rm -f /etc/cni/net.d/*.conflist
        sudo cp .github/actions/cni-10-bridge.conflist /etc/cni/net.d/10-bridge.conflist

        sudo mkdir -p /etc/containerd
        # remove the default config which has disabled_plugins = ["cri"]
        sudo rm -f /etc/containerd/config.toml
        sudo cp .github/actions/containerd-config-k3s.toml /etc/containerd/
        diff -u <( sudo containerd config default ) <( sudo containerd config dump ) || true
        sudo systemctl restart containerd
        sudo ctr version
      shell: bash -euxo pipefail {0}
