name: Install and start K3s
runs:
  using: composite
  steps:
    - run: |
        export INSTALL_K3S_EXEC
        if [ -e /var/run/crio/crio.sock ] ; then
            INSTALL_K3S_EXEC='--flannel-backend=none --container-runtime-endpoint /var/run/crio/crio.sock'
            ( echo '[crio.network]' ; echo 'plugin_dirs = [ "/var/lib/rancher/k3s/data/cni" ]' ) | sudo tee /etc/crio/crio.conf.d/20-cni.conf
            sudo systemctl restart crio.service
        elif [ -e /run/containerd/containerd.sock ] ; then
            INSTALL_K3S_EXEC='--flannel-backend=none  --container-runtime-endpoint /run/containerd/containerd.sock'
        fi
        curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig ~/.kube/config --write-kubeconfig-group $( id -g ) --write-kubeconfig-mode 640 --disable=traefik --disable=metrics-server
      shell: bash -euxo pipefail {0}
