name: Install and start K3s
runs:
  using: composite
  steps:
    - run: |
        export INSTALL_K3S_EXEC
        if [ -e /var/run/crio/crio.sock ] ; then
            INSTALL_K3S_EXEC='--flannel-backend=none --container-runtime-endpoint /var/run/crio/crio.sock'
            ( echo '[crio.network]' ; echo 'plugin_dirs = [ "/var/lib/rancher/k3s/data/cni" ]' ) | sudo tee /etc/crio/crio.conf.d/20-cni.conf
            sudo systemctl restart crio.service
        elif [ -e /run/containerd/containerd.sock ] ; then
            INSTALL_K3S_EXEC='--flannel-backend=none  --container-runtime-endpoint /run/containerd/containerd.sock'
            if [ -f /etc/containerd/containerd-config-k3s.toml ] ; then
                sudo cp /etc/containerd/containerd-config-k3s.toml /etc/containerd/config.toml
                diff -u <( sudo containerd config default ) <( sudo containerd config dump ) || true
                sudo systemctl restart containerd
            fi
        fi
        curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig ~/.kube/config --disable=traefik --disable=metrics-server
        sudo chown -R $( id -u ):$( id -g ) ~/.kube
        ( set +x ; while true ; do if kubectl get nodes | tee /dev/stderr | grep -q '\bReady\b' ; then break ; else sleep 5 ; fi ; done )
        ( set +x ; while ! kubectl get serviceaccount/default ; do sleep 5 ; done )
        kubectl get pods --all-namespaces
        ( set +x ; while kubectl get pods -A 2>&1 | grep -E 'Pending|ContainerCreating|Init|No resources found' ; do echo --- ; sleep 5 ; done )
        kubectl get all -A
      shell: bash -euxo pipefail {0}
