
name: Kind in podman

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  kind-in-k3s:
    name: Kind in K3s
    runs-on: ubuntu-24.04${{ matrix.arch == 'arm64' && '-arm' || '' }}
    strategy:
      fail-fast: false
      matrix:
        arch: [ arm64 ]
        kubernetes: [ k3s, "kubeadm init", rke2, k0s ]
        runtime: [ cri-o, containerd, default ]
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - run: date '+%F %T' > job-start
      - name: Stop the default containerd
        run: |
          sudo systemctl stop containerd
      - uses: ./.github/actions/install-crio
        env:
          CRIO_VERSION: v1.34
        if: matrix.runtime == 'cri-o'
      - uses: ./.github/actions/install-containerd-2.2
        if: matrix.runtime == 'containerd'
      - uses: ./.github/actions/install-k8s
        env:
          KUBERNETES_VERSION: v1.34
        if: matrix.kubernetes == 'kubeadm init'
      - uses: ./.github/actions/install-k3s
        if: matrix.kubernetes == 'k3s'
      - uses: ./.github/actions/install-rke2
        if: matrix.kubernetes == 'rke2'
      - uses: ./.github/actions/install-k0s
        if: matrix.kubernetes == 'k0s'

      - name: Build image
        run: docker build -t localhost/kind .
      - run: sudo skopeo copy docker-daemon:localhost/kind:latest containers-storage:localhost/kind
        if: matrix.runtime == 'cri-o'
      - run: docker save localhost/kind | sudo ctr -n k8s.io images import -
        if: matrix.runtime == 'containerd'
      - run: docker save localhost/kind | sudo k3s ctr images import -
        if: matrix.runtime == 'default'
      - run: sudo systemctl stop docker.service docker.socket

      - name: Wait for the cluster to become ready
        run: while ! kubectl get nodes ; do sleep 5 ; done ; kubectl get nodes -o jsonpath='{.items[*].metadata.name}' | xargs kubectl wait --for=condition=ready node
      - run: kubectl get all -A
      - run: while ! kubectl get serviceaccount/default ; do sleep 5 ; done
      - run: kubectl apply -f - < kind-cluster-pod-k3s.yaml
      - run: while ! kubectl get pod/kind-cluster -o jsonpath="{.status.initContainerStatuses[0].state['running','terminated'].startedAt}" | grep . ; do kubectl get pod/kind-cluster ; sleep 5 ; done
      - run: kubectl logs -f pod/kind-cluster -c create-cluster
      - run: kubectl describe pod/kind-cluster
      - run: kubectl get pod/kind-cluster -o jsonpath="{.status.initContainerStatuses[0].state['terminated'].exitCode}" | grep ^0$
      - run: while ! kubectl get pod/kind-cluster -o jsonpath="{.status.containerStatuses[0].state['running','terminated'].startedAt}" | grep . ; do kubectl get pod/kind-cluster ; sleep 5 ; done
      - run: kubectl logs pod/kind-cluster
      - run: kubectl get pod/kind-cluster
      - run: kubectl describe pod/kind-cluster
      - run: kubectl exec pod/kind-cluster -- podman ps -a
      - run: while ! kubectl exec pod/kind-cluster -- curl -ks https://127.0.0.1:6443/ ; do sleep 1 ; done
      - run: kubectl exec pod/kind-cluster -- kubectl get nodes -o jsonpath='{.items[*].metadata.name}' | xargs kubectl exec pod/kind-cluster -- kubectl wait --for=condition=ready node
      - run: kubectl exec pod/kind-cluster -- kubectl get nodes
      - run: kubectl exec pod/kind-cluster -- kubectl get all -A

      - run: kubectl exec pod/kind-cluster -- kubectl create serviceaccount -n default admin
      - run: kubectl exec pod/kind-cluster -- kubectl patch clusterrolebinding cluster-admin --type=json -p='[{"op":"add", "path":"/subjects/-", "value":{"kind":"ServiceAccount", "namespace":"default", "name":"admin" } }]'
      - run: kubectl --kubeconfig=./kubeconfig config set-cluster kind --server=https://$( kubectl get service/kind-cluster -o jsonpath='{.spec.clusterIP}:{.spec.ports[0].port}' ) --insecure-skip-tls-verify=true
      - run: kubectl --kubeconfig=./kubeconfig config set-credentials kind-admin --token=$( kubectl exec pod/kind-cluster -- kubectl create token -n default admin )
      - run: kubectl --kubeconfig=./kubeconfig config set-context kind --cluster=kind --user=kind-admin
      - run: kubectl --kubeconfig=./kubeconfig config use-context kind
      - run: kubectl --kubeconfig=./kubeconfig get all -A

      - run: kubectl delete pod/kind-cluster
      - run: kubectl apply -f - < kind-cluster-pod-k3s.yaml
      - run: while ! kubectl get pod/kind-cluster -o jsonpath="{.status.containerStatuses[0].state['running','terminated'].startedAt}" | grep . ; do kubectl get pod/kind-cluster ; sleep 5 ; done
      - run: kubectl logs pod/kind-cluster -c create-cluster
      - run: kubectl logs pod/kind-cluster
      - run: while ! kubectl exec pod/kind-cluster -- curl -ks https://127.0.0.1:6443/ ; do sleep 1 ; done
      - run: kubectl exec pod/kind-cluster -- kubectl get all -A

      - run: kubectl --kubeconfig=./kubeconfig get all -A

      - run: sudo journalctl -u k3s -S "$( cat job-start )" -l > k3s.log
        if: failure() && matrix.kubernetes == 'k3s'
      - run: kubectl describe nodes
        if: failure()
      - uses: actions/upload-artifact@v4
        with:
          name: k3s-log-${{ matrix.runtime }}-${{matrix.arch}}
          path: k3s.log
        if: failure() && matrix.kubernetes == 'k3s'

