
name: Kind in podman

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  kind-in-microshift:
    name: Kind in MicroShift
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    env:
      CRIO_VERSION: 1.25
      MICROSHIFT_VERSION: latest-4.14/el9/os/Packages/microshift-4.14.0~rc.7-202310241737.p0.g1586504.assembly.rc.7.el9__x86_64/microshift-4.14.0~rc.7-202310241737.p0.g1586504.assembly.rc.7.el9.x86_64.rpm
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt update \
          && sudo apt install -y openvswitch-switch network-manager
      - run: sudo ln -s openvswitch-switch.service /lib/systemd/system/openvswitch.service
      - run: sudo systemctl daemon-reload
      - name: Install CRI-O
        run: |
          sudo mkdir -p /etc/apt/keyrings \
          && curl -fsSL https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_$(lsb_release -rs)/Release.key \
            | gpg --dearmor \
            | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_stable.gpg > /dev/null \
          && echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_stable.gpg] \
            https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_$(lsb_release -rs)/ /" \
            | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list > /dev/null \
          && curl -fsSL https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$CRIO_VERSION/xUbuntu_$(lsb_release -rs)/Release.key \
            | gpg --dearmor \
            | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_crio.gpg > /dev/null \
          && echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_crio.gpg] \
            https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$CRIO_VERSION/xUbuntu_$(lsb_release -rs)/ /" \
            | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:$CRIO_VERSION.list > /dev/null \
          && sudo apt update \
          && sudo apt install -y cri-o crun cri-tools containernetworking-plugins
      - run: sudo mkdir -p /var/run/crio /var/lib/crio
      - run: ls -la /etc/cni/net.d && cat /etc/cni/net.d/100-crio-bridge.conf
      - run: ( echo '[crio.network]' ; echo 'plugin_dirs = [ "/usr/lib/cni/" ]' ) | sudo tee /etc/crio/crio.conf.d/zz-plugin_dirs.conf
      - run: echo '${{ secrets.PULL_SECRET }}' > openshift-pull-secret && sudo mv openshift-pull-secret /etc/crio/ && sudo chown root:root /etc/crio/openshift-pull-secret && sudo chmod 600 /etc/crio/openshift-pull-secret
      - run: |
          for i in $MICROSHIFT_VERSION ${MICROSHIFT_VERSION/x86_64\/microshift-/x86_64\/microshift-networking-} ; do \
            curl -LO https://mirror.openshift.com/pub/openshift-v4/x86_64/microshift/ocp/$i ; done
      - run: for i in *.rpm ; do rpm2cpio $i | ( cd / && sudo cpio -id ) ; done
      - run: sudo cp crio-crun.conf /etc/crio/crio.conf.d/crun.conf
      - run: sudo systemctl daemon-reload

      - run: sudo systemctl enable crio.service microshift.service --now
      - run: sudo systemctl status crio.service
      - run: sudo crictl --version
      - run: sudo crictl info
      - run: sudo systemctl status microshift.service
      - run: mkdir -p ~/.kube && sudo cat /var/lib/microshift/resources/kubeadmin/kubeconfig > ~/.kube/config
      - run: kubectl get all -A

      - name: Debug with upterm on failure
        if: always()
        uses: lhotari/action-upterm@v1
        with:
          limit-access-to-actor: true

